CREATE DATABASE pijamas;
USE pijamas;
CREATE TABLE IF NOT EXISTS Clientes(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDOS VARCHAR(100),
DIRECCION TEXT,
TELEFONO VARCHAR(20),
UNIQUE (ID_CLIENTE)
);
CREATE TABLE productos (
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(250),
PRECIO DECIMAL (10, 2)
);
CREATE TABLE Vendedor(
ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100),
DIRECCION VARCHAR(255)
);
CREATE TABLE Facturas(
ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
FECHA DATE,
ID_CLIENTE INT,
CONSTRAINT fk_cliente_factura FOREIGN KEY (ID_CLIENTE)
REFERENCES Clientes (ID_CLIENTE)
);
CREATE TABLE Ventas(
ID_VENTAS INT PRIMARY KEY AUTO_INCREMENT,
ID_FACTURA INT,
ID_PRODUCTO INT,
ID_VENDEDOR INT,
CONSTRAINT fk_factura_venta FOREIGN KEY (ID_FACTURA)
REFERENCES Facturas(ID_FACTURA),
CONSTRAINT fk_vendedor_venta FOREIGN KEY (ID_VENDEDOR)
REFERENCES Vendedor(ID_VENDEDOR),
CONSTRAINT fk_producto_venta FOREIGN KEY (ID_PRODUCTO) 
REFERENCES productos(ID_PRODUCTO) 
);

